language: php
php:
  - '5.6'
  - '7.1'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'USE test;'
  - mysql -e 'CREATE TABLE test.post ( 
                                         post_id int NOT NULL auto_increment, 
                                         title varchar(255),
                                         contents varchar(255), 
                                         date_created datetime DEFAULT NULL, 
                                         rating int DEFAULT '0'  NULL, 
                                         PRIMARY KEY (`post_id`)
                                         ) 
                                         CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
