dist: trusty
sudo: required
language: php
php:
  - '5.6'
  - '7.1'
services:
  - mysql
before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS `test`;'
  - mysql -u root -e 'USE `test`;'
  - mysql -u root -e 'CREATE TABLE `post`( 
                                         post_id int NOT NULL auto_increment, 
                                         title varchar(255), 
                                         date_created datetime DEFAULT NULL, 
                                         rating int DEFAULT '0' NOT NULL, 
                                         PRIMARY KEY (post_id)
                                         ) 
                                         CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
